### ISSUE TITLE
could you provide the demo2.mp4 in your code?

### ISSUE THREAD

**Issue by ForrestPi** [SummerSigh/TheVrMLEyeToolbox#6]
Hi, 
`cap = cv2.VideoCapture("demo2.mp4")`
could you provide the demo2.mp4 in your code for test?

**Comment by SummerSigh** [comment]
BAM! 

https://user-images.githubusercontent.com/71572746/167343841-b5f427ae-6bf4-4bd0-aa49-dcac3634cc62.mp4

have fun!

**Comment by SummerSigh** [comment]
i should probably add that
